/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PrixDirectory {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
    'styling'?: any;
  }
  interface PrixModal {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
    'styling'?: any;
  }
}

declare global {


  interface HTMLPrixDirectoryElement extends Components.PrixDirectory, HTMLStencilElement {}
  var HTMLPrixDirectoryElement: {
    prototype: HTMLPrixDirectoryElement;
    new (): HTMLPrixDirectoryElement;
  };

  interface HTMLPrixModalElement extends Components.PrixModal, HTMLStencilElement {}
  var HTMLPrixModalElement: {
    prototype: HTMLPrixModalElement;
    new (): HTMLPrixModalElement;
  };
  interface HTMLElementTagNameMap {
    'prix-directory': HTMLPrixDirectoryElement;
    'prix-modal': HTMLPrixModalElement;
  }
}

declare namespace LocalJSX {
  interface PrixDirectory extends JSXBase.HTMLAttributes<HTMLPrixDirectoryElement> {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
    'styling'?: any;
  }
  interface PrixModal extends JSXBase.HTMLAttributes<HTMLPrixModalElement> {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
    'styling'?: any;
  }

  interface IntrinsicElements {
    'prix-directory': PrixDirectory;
    'prix-modal': PrixModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


