/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PrixDirectory {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
  }
}

declare global {


  interface HTMLPrixDirectoryElement extends Components.PrixDirectory, HTMLStencilElement {}
  var HTMLPrixDirectoryElement: {
    prototype: HTMLPrixDirectoryElement;
    new (): HTMLPrixDirectoryElement;
  };
  interface HTMLElementTagNameMap {
    'prix-directory': HTMLPrixDirectoryElement;
  }
}

declare namespace LocalJSX {
  interface PrixDirectory extends JSXBase.HTMLAttributes<HTMLPrixDirectoryElement> {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
  }

  interface IntrinsicElements {
    'prix-directory': PrixDirectory;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


