/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PrixDirectory {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
    'styling'?: any;
  }
  interface PrixDirectoryItem {
    /**
    * COMMON ATTRIBUTES
    */
    'color': string;
    'item'?: any;
  }
  interface PrixDrawer {
    /**
    * Common attributes
    */
    'color': string;
    'expandSize': string;
    'hideDrawer': () => Promise<void>;
    'opacity': boolean;
    'overflowY': boolean;
    /**
    * Public API
    */
    'showDrawer': () => Promise<void>;
    'side': string;
  }
  interface PrixModal {
    'acceptLabel': string;
    'acceptLabelColor': string;
    'acceptLabelColorText': string;
    'cancelLabel': string;
    'cancelLabelColor': string;
    'cancelLabelColorText': string;
    'colorBody': string;
    'colorBodyText': string;
    'colorFooter': string;
    /**
    * Common attributes
    */
    'colorHeader': string;
    'colorHeaderText': string;
    'expandSizeWidth': string;
    'hideModal': () => Promise<void>;
    'onCancelEvent': () => Promise<void>;
    /**
    * Public API Methods
    */
    'onOkEvent': () => Promise<void>;
    'showModal': () => Promise<void>;
  }
  interface PrixMultiLevel {
    'color': string;
    'dark': boolean;
    'data'?: any;
    /**
    * COMMON ATTRIBUTES
    */
    'message': string;
  }
}

declare global {


  interface HTMLPrixDirectoryElement extends Components.PrixDirectory, HTMLStencilElement {}
  var HTMLPrixDirectoryElement: {
    prototype: HTMLPrixDirectoryElement;
    new (): HTMLPrixDirectoryElement;
  };

  interface HTMLPrixDirectoryItemElement extends Components.PrixDirectoryItem, HTMLStencilElement {}
  var HTMLPrixDirectoryItemElement: {
    prototype: HTMLPrixDirectoryItemElement;
    new (): HTMLPrixDirectoryItemElement;
  };

  interface HTMLPrixDrawerElement extends Components.PrixDrawer, HTMLStencilElement {}
  var HTMLPrixDrawerElement: {
    prototype: HTMLPrixDrawerElement;
    new (): HTMLPrixDrawerElement;
  };

  interface HTMLPrixModalElement extends Components.PrixModal, HTMLStencilElement {}
  var HTMLPrixModalElement: {
    prototype: HTMLPrixModalElement;
    new (): HTMLPrixModalElement;
  };

  interface HTMLPrixMultiLevelElement extends Components.PrixMultiLevel, HTMLStencilElement {}
  var HTMLPrixMultiLevelElement: {
    prototype: HTMLPrixMultiLevelElement;
    new (): HTMLPrixMultiLevelElement;
  };
  interface HTMLElementTagNameMap {
    'prix-directory': HTMLPrixDirectoryElement;
    'prix-directory-item': HTMLPrixDirectoryItemElement;
    'prix-drawer': HTMLPrixDrawerElement;
    'prix-modal': HTMLPrixModalElement;
    'prix-multi-level': HTMLPrixMultiLevelElement;
  }
}

declare namespace LocalJSX {
  interface PrixDirectory extends JSXBase.HTMLAttributes<HTMLPrixDirectoryElement> {
    'configuration'?: any;
    /**
    * Common attributes
    */
    'data'?: any;
    'styling'?: any;
  }
  interface PrixDirectoryItem extends JSXBase.HTMLAttributes<HTMLPrixDirectoryItemElement> {
    /**
    * COMMON ATTRIBUTES
    */
    'color'?: string;
    'item'?: any;
  }
  interface PrixDrawer extends JSXBase.HTMLAttributes<HTMLPrixDrawerElement> {
    /**
    * Common attributes
    */
    'color'?: string;
    'expandSize'?: string;
    'opacity'?: boolean;
    'overflowY'?: boolean;
    'side'?: string;
  }
  interface PrixModal extends JSXBase.HTMLAttributes<HTMLPrixModalElement> {
    'acceptLabel'?: string;
    'acceptLabelColor'?: string;
    'acceptLabelColorText'?: string;
    'cancelLabel'?: string;
    'cancelLabelColor'?: string;
    'cancelLabelColorText'?: string;
    'colorBody'?: string;
    'colorBodyText'?: string;
    'colorFooter'?: string;
    /**
    * Common attributes
    */
    'colorHeader'?: string;
    'colorHeaderText'?: string;
    'expandSizeWidth'?: string;
    'onTriggerCancel'?: (event: CustomEvent<any>) => void;
    /**
    * Event Emmitters
    */
    'onTriggerOk'?: (event: CustomEvent<any>) => void;
  }
  interface PrixMultiLevel extends JSXBase.HTMLAttributes<HTMLPrixMultiLevelElement> {
    'color'?: string;
    'dark'?: boolean;
    'data'?: any;
    /**
    * COMMON ATTRIBUTES
    */
    'message'?: string;
  }

  interface IntrinsicElements {
    'prix-directory': PrixDirectory;
    'prix-directory-item': PrixDirectoryItem;
    'prix-drawer': PrixDrawer;
    'prix-modal': PrixModal;
    'prix-multi-level': PrixMultiLevel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


