/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppMenu {
    'message': string;
  }
}

declare global {


  interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {}
  var HTMLAppMenuElement: {
    prototype: HTMLAppMenuElement;
    new (): HTMLAppMenuElement;
  };
  interface HTMLElementTagNameMap {
    'app-menu': HTMLAppMenuElement;
  }
}

declare namespace LocalJSX {
  interface AppMenu extends JSXBase.HTMLAttributes<HTMLAppMenuElement> {
    'message'?: string;
  }

  interface IntrinsicElements {
    'app-menu': AppMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


